version: "3.8"

services:
  web:
    image: php:8.2-apache
    container_name: envanter_web
    volumes:
      - ./public:/var/www/html/
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: envanter_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: envanter
      MYSQL_USER: envanteruser
      MYSQL_PASSWORD: envanterpass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: envanter_pma
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8081:80"
    restart: always
